In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

- Como agregar variables categoricas a una regresion lineal

- Train / test

- Cross validation (K Fold)

In [2]:
df = pd.read_csv('data/csvs/examenes.csv')
df

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19997,18,other,bba,6.50,71.3,yes,5.0,good,self-study,low,easy,86.5
19996,19998,18,male,b.com,3.71,41.6,no,5.9,average,coaching,medium,moderate,60.9
19997,19999,19,other,diploma,7.88,68.2,yes,4.6,poor,group study,low,easy,64.5
19998,20000,19,male,bba,4.60,76.3,no,6.1,good,self-study,medium,moderate,79.0
19999,20001,20,male,b.sc,7.50,47.9,yes,7.5,poor,coaching,medium,moderate,71.0

In [3]:
df["study_method"].unique()

<StringArray>
['coaching', 'online videos', 'mixed', 'self-study', 'group study']
Length: 5, dtype: str

In [4]:
df

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19997,18,other,bba,6.50,71.3,yes,5.0,good,self-study,low,easy,86.5
19996,19998,18,male,b.com,3.71,41.6,no,5.9,average,coaching,medium,moderate,60.9
19997,19999,19,other,diploma,7.88,68.2,yes,4.6,poor,group study,low,easy,64.5
19998,20000,19,male,bba,4.60,76.3,no,6.1,good,self-study,medium,moderate,79.0
19999,20001,20,male,b.sc,7.50,47.9,yes,7.5,poor,coaching,medium,moderate,71.0

In [5]:
df["study_method"].unique()

<StringArray>
['coaching', 'online videos', 'mixed', 'self-study', 'group study']
Length: 5, dtype: str

In [6]:
lista1 = ["a","b","c"]
lista2 = ["a","b","c","d","f"]

nuevas_columnas = 2
lista2[-nuevas_columnas:]

['d', 'f']

In [7]:
prueba = [0,1,2,3,4,5]
prueba[-4:]

[2, 3, 4, 5]

In [8]:
df_encoded = pd.get_dummies(df, columns=["study_method"], dtype=int, drop_first=True)
df_encoded

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,facility_rating,exam_difficulty,exam_score,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,low,hard,58.9,0,0,0,0
1,2,23,other,bca,3.37,64.8,yes,4.6,average,medium,moderate,54.8,0,0,1,0
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,high,moderate,90.3,0,0,0,0
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,low,moderate,29.7,0,0,1,0
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,low,moderate,43.7,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19997,18,other,bba,6.50,71.3,yes,5.0,good,low,easy,86.5,0,0,0,1
19996,19998,18,male,b.com,3.71,41.6,no,5.9,average,medium,moderate,60.9,0,0,0,0
19997,19999,19,other,diploma,7.88,68.2,yes,4.6,poor,low,easy,64.5,1,0,0,0
19998,20000,19,male,bba,4.60,76.3,no,6.1,good,medium,moderate,79.0,0,0,0,1
19999,20001,20,male,b.sc,7.50,47.9,yes,7.5,poor,medium,moderate,71.0,0,0,0,0

In [9]:
#df_encoded = pd.get_dummies(df, columns=["study_method"])
#columnas_nuevas = len(df["study_method"].unique())
#nombre_columnas_nuevas = df_encoded.columns[-columnas_nuevas:]
#print(nombre_columnas_nuevas)

#for columna in nombre_columnas_nuevas:
#    df_encoded[columna] = df_encoded[columna].astype(int)

In [10]:
var_objetivo = "exam_score"
variables_predicivas = ["study_hours"]

columnas_nuevas = len(df["study_method"].unique()) - 1
nombre_columnas_nuevas = list(df_encoded.columns[-columnas_nuevas:])
variables_predicivas = variables_predicivas + nombre_columnas_nuevas
print(variables_predicivas)

#Para obtener la lista de las variables predictivas, sabiendo que study hours es una de ellas
#y study_mthod tmb pero se agregaron columnas binarias apartir de los valores de study_method

X = df_encoded[variables_predicivas]
y = df_encoded[var_objetivo]

['study_hours', 'study_method_group study', 'study_method_mixed', 'study_method_online videos', 'study_method_self-study']

# Train / test

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

import statsmodels.api as sm

#X_train = sm.add_constant(X_train)

model = sm.OLS(y_train, X_train)

result = model.fit()

result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:             exam_score   R-squared (uncentered):                   0.902
Model:                            OLS   Adj. R-squared (uncentered):              0.902
Method:                 Least Squares   F-statistic:                          2.589e+04
Date:                Tue, 31 Mar 2026   Prob (F-statistic):                        0.00
Time:                        18:36:13   Log-Likelihood:                         -62057.
No. Observations:               14000   AIC:                                  1.241e+05
Df Residuals:                   13995   BIC:                                  1.242e+05
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
study_hours                   10.1328      0.059    171.788      0.000      10.017      10.248
study_method_group study      20.8817      0.452     46.233      0.000      19.996      21.767
study_method_mixed            23.1469      0.455     50.830      0.000      22.254      24.040
study_method_online videos    18.9436      0.452     41.909      0.000      18.058      19.830
study_method_self-study       18.6801      0.446     41.907      0.000      17.806      19.554
==============================================================================
Omnibus:                      220.412   Durbin-Watson:                   1.856
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              230.754
Skew:                           0.314   Prob(JB):                     7.80e-51
Kurtosis:                       2.986   Cond. No.                         16.4
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [12]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#predicciones para ambos conjunts
predicciones_train = result.predict(X_train)
predicciones_test = result.predict(X_test)



#Train
print(mean_squared_error(y_train, predicciones_train) ** 0.5)

#Test
print(mean_squared_error(y_test, predicciones_test) ** 0.5)

20.36331854793748
20.520127841975448

In [17]:
y

0        58.9
1        54.8
2        90.3
3        29.7
4        43.7
         ...
19995    86.5
19996    60.9
19997    64.5
19998    79.0
19999    71.0
Name: exam_score, Length: 20000, dtype: float64

In [18]:
np.array(X)

array([[2.78, 0.  , 0.  , 0.  , 0.  ],
       [3.37, 0.  , 0.  , 1.  , 0.  ],
       [7.88, 0.  , 0.  , 0.  , 0.  ],
       ...,
       [7.88, 1.  , 0.  , 0.  , 0.  ],
       [4.6 , 0.  , 0.  , 0.  , 1.  ],
       [7.5 , 0.  , 0.  , 0.  , 0.  ]], shape=(20000, 5))

# K - FOLD Cross Validation

In [26]:
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.metrics import mean_squared_error

#Hacer que X y Y sean arreglos de numpy
X = np.array(X)
y = np.array(y)


# Configurar el K-Fold
kf = KFold(n_splits=10, shuffle=True, random_state=42)

#Crear listas de las metricas
lista_mse = []
lista_rmse = []
lista_rmse_train = []

# Iteracion sobre los folds

for train_index, test_index in kf.split(X):
    #Dividir X y Y en train/test
    X_train = X[train_index]
    X_test = X[test_index]
    y_train = y[train_index]
    y_test = y[test_index]
    
    #Entrenamiento del modelo
    model = sm.OLS(y_train, X_train).fit()

    #Obtener metricas para el entrenamiento
    predicciones_train = model.predict(X_train)
    rmse_train = mean_squared_error(y_train, predicciones_train) ** 0.5
    lista_rmse_train.append(rmse_train)

    #Obtener metricas para el test
    predicciones = model.predict(X_test)
    mse = mean_squared_error(y_test, predicciones)
    rmse = mse ** 0.5

    #Agregar cada metrica en su lista
    lista_mse.append(mse)
    lista_rmse.append(rmse)

lista_mse = np.array(lista_mse)
lista_rmse = np.array(lista_rmse)
lista_rmse_train = np.array(lista_rmse_train)

print("Media de MSE K - FOLD", lista_mse.mean())
print("Desv Estandar de MSE K - FOLD", lista_mse.std())

print("\n")


print("Media de RMSE K - FOLD", lista_rmse.mean())
print("Desv Estandar de RMSE K - FOLD", lista_rmse.std())


print("\n")


print("Media de RMSE K - FOLD (TRAIN)", lista_rmse_train.mean())
print("Desv Estandar de RMSE K - FOLD (TRAIN)", lista_rmse_train.std())

Media de MSE K - FOLD 416.69557707705854
Desv Estandar de MSE K - FOLD 11.502599728159414


Media de RMSE K - FOLD 20.41118105524989
Desv Estandar de RMSE K - FOLD 0.2815404178204185


Media de RMSE K - FOLD (TRAIN) 20.409740346032454
Desv Estandar de RMSE K - FOLD (TRAIN) 0.03130318374980203

# Leave one out Cross validation (LOOCV)

In [23]:
from sklearn.model_selection import LeaveOneOut

loo = LeaveOneOut()
lista_rmse = []

#Anadir columna de unos para el intercepto/bias/beta 0
#X = sm.add_constant(X)

for train_index, test_index in loo.split(X):
    X_train = X[train_index]
    X_test = X[test_index]
    y_train = y[train_index]
    y_test = y[test_index]
    #Entreamiento

    model = sm.OLS(y_train, X_train).fit()

    #Obtener metrica 
    predicciones = model.predict(X_test)
    rmse = mean_squared_error(y_test, predicciones) ** 0.5
    lista_rmse.append(rmse)

lista_rmse = np.array(lista_rmse)

print("Media de RMSE LOOCV", lista_rmse.mean())
print("Desv Estandar de RMSE LOOCV", lista_rmse.std())

Media de RMSE LOOCV 16.005081248063217
Desv Estandar de RMSE LOOCV 12.670848708931402